// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPd3icYzRpsmwjhSSrCrMTcpEEFc3pxC8',
    appId: '1:445352542909:web:058accbd7589a8a9026dd4',
    messagingSenderId: '445352542909',
    projectId: 'tallys-financeiro',
    authDomain: 'tallys-financeiro.firebaseapp.com',
    storageBucket: 'tallys-financeiro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkyA67SQngz0EiWbcVAkdZOTnL7mxXFxo',
    appId: '1:445352542909:android:5059b618c96ccc14026dd4',
    messagingSenderId: '445352542909',
    projectId: 'tallys-financeiro',
    storageBucket: 'tallys-financeiro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3fdiy0tTz4HEP2OQCjFEePBh4ImERq8I',
    appId: '1:445352542909:ios:ed32bc5a823ea522026dd4',
    messagingSenderId: '445352542909',
    projectId: 'tallys-financeiro',
    storageBucket: 'tallys-financeiro.firebasestorage.app',
    iosBundleId: 'com.example.fluxo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3fdiy0tTz4HEP2OQCjFEePBh4ImERq8I',
    appId: '1:445352542909:ios:ed32bc5a823ea522026dd4',
    messagingSenderId: '445352542909',
    projectId: 'tallys-financeiro',
    storageBucket: 'tallys-financeiro.firebasestorage.app',
    iosBundleId: 'com.example.fluxo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPd3icYzRpsmwjhSSrCrMTcpEEFc3pxC8',
    appId: '1:445352542909:web:0e1e0ac48a4db539026dd4',
    messagingSenderId: '445352542909',
    projectId: 'tallys-financeiro',
    authDomain: 'tallys-financeiro.firebaseapp.com',
    storageBucket: 'tallys-financeiro.firebasestorage.app',
  );
}
